# Generated by Django 5.2.17 on 2026-08-13 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("employees", "0007_contract_document_helpers"),
        ("org", "0002_alter_branch_timezone"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="حُدّث في"),
                ),
                (
                    "first_name_ar",
                    models.CharField(max_length=100, verbose_name="الاسم (عربي)"),
                ),
                (
                    "last_name_ar",
                    models.CharField(max_length=100, verbose_name="اللقب (عربي)"),
                ),
                (
                    "first_name_fr",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="الاسم (فرنسي)"
                    ),
                ),
                (
                    "last_name_fr",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="اللقب (فرنسي)"
                    ),
                ),
                (
                    "first_name_en",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="الاسم (إنجليزي)"
                    ),
                ),
                (
                    "last_name_en",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="اللقب (إنجليزي)"
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="البريد الإلكتروني"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=30, verbose_name="الهاتف"),
                ),
                (
                    "source",
                    models.CharField(blank=True, max_length=30, verbose_name="المصدر"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "جديد"),
                            ("screening", "قيد الفرز"),
                            ("interviewed", "تمت المقابلة"),
                            ("offer", "عرض وظيفي"),
                            ("hired", "تم التوظيف"),
                            ("rejected", "مرفوض"),
                            ("withdrawn", "انسحب"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "resume",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="recruitment/resumes/",
                        verbose_name="السيرة الذاتية",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "applied_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ التقديم"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشأه",
                    ),
                ),
                (
                    "hired_employee",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="employees.employee",
                        verbose_name="الموظف المعيّن",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="حدّثه",
                    ),
                ),
            ],
            options={
                "verbose_name": "مرشح",
                "verbose_name_plural": "المرشحون",
                "ordering": ("-applied_date", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="حُدّث في"),
                ),
                ("scheduled_at", models.DateTimeField(verbose_name="موعد المقابلة")),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("in_person", "حضوري"),
                            ("phone", "هاتف"),
                            ("video", "فيديو"),
                        ],
                        default="in_person",
                        max_length=20,
                        verbose_name="الطريقة",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "مجدولة"),
                            ("completed", "مكتملة"),
                            ("cancelled", "ملغاة"),
                        ],
                        default="scheduled",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="الدرجة (0-100)"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="الملاحظات")),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interviews",
                        to="recruitment.candidate",
                        verbose_name="المرشح",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشأه",
                    ),
                ),
                (
                    "interviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المحاور",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="حدّثه",
                    ),
                ),
            ],
            options={
                "verbose_name": "مقابلة",
                "verbose_name_plural": "المقابلات",
                "ordering": ("scheduled_at",),
            },
        ),
        migrations.CreateModel(
            name="JobPosting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="حُدّث في"),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="رمز الإعلان"
                    ),
                ),
                (
                    "title_ar",
                    models.CharField(max_length=200, verbose_name="العنوان (عربي)"),
                ),
                (
                    "title_fr",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="العنوان (فرنسي)"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="العنوان (إنجليزي)"
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full_time", "دوام كامل"),
                            ("part_time", "دوام جزئي"),
                            ("contract", "عقد محدد"),
                            ("internship", "تدريب مهني"),
                        ],
                        default="full_time",
                        max_length=20,
                        verbose_name="نوع التوظيف",
                    ),
                ),
                (
                    "openings_count",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="عدد الشواغر"
                    ),
                ),
                (
                    "requirements",
                    models.TextField(blank=True, verbose_name="المتطلبات"),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("published", "منشور"),
                            ("closed", "مغلق"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "publish_date",
                    models.DateField(blank=True, null=True, verbose_name="تاريخ النشر"),
                ),
                (
                    "close_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ الإغلاق"
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="job_postings",
                        to="org.branch",
                        verbose_name="الفرع",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشأه",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="job_postings",
                        to="org.department",
                        verbose_name="القسم",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="حدّثه",
                    ),
                ),
            ],
            options={
                "verbose_name": "إعلان وظيفة",
                "verbose_name_plural": "إعلانات الوظائف",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddField(
            model_name="candidate",
            name="posting",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="candidates",
                to="recruitment.jobposting",
                verbose_name="الإعلان",
            ),
        ),
    ]
