# Generated by Django 5.2.17 on 2026-08-13 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("employees", "0007_contract_document_helpers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="حُدّث في"),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="رمز الدورة"
                    ),
                ),
                (
                    "title_ar",
                    models.CharField(max_length=200, verbose_name="العنوان (عربي)"),
                ),
                (
                    "title_fr",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="العنوان (فرنسي)"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="العنوان (إنجليزي)"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "category",
                    models.CharField(blank=True, max_length=50, verbose_name="الفئة"),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="المزوّد"
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="التكلفة",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشأه",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="حدّثه",
                    ),
                ),
            ],
            options={
                "verbose_name": "دورة تدريبية",
                "verbose_name_plural": "الدورات التدريبية",
                "ordering": ("code",),
            },
        ),
        migrations.CreateModel(
            name="TrainingEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="حُدّث في"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد الانتظار"),
                            ("approved", "معتمد"),
                            ("completed", "مكتمل"),
                            ("failed", "فاشل"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="وقت الاعتماد"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="اعتمده",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشأه",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_enrollments",
                        to="employees.employee",
                        verbose_name="الموظف",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="حدّثه",
                    ),
                ),
            ],
            options={
                "verbose_name": "تسجيل تدريبي",
                "verbose_name_plural": "التسجيلات التدريبية",
                "ordering": ("session__start_date", "employee__employee_code"),
            },
        ),
        migrations.CreateModel(
            name="TrainingCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="حُدّث في"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="العنوان")),
                ("issued_date", models.DateField(verbose_name="تاريخ الإصدار")),
                (
                    "file_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="مسار الملف"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشأه",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="حدّثه",
                    ),
                ),
                (
                    "enrollment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificate",
                        to="training.trainingenrollment",
                        verbose_name="التسجيل",
                    ),
                ),
            ],
            options={
                "verbose_name": "شهادة تدريب",
                "verbose_name_plural": "شهادات التدريب",
                "ordering": ("-issued_date",),
            },
        ),
        migrations.CreateModel(
            name="TrainingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="حُدّث في"),
                ),
                ("start_date", models.DateField(verbose_name="تاريخ البدء")),
                ("end_date", models.DateField(verbose_name="تاريخ الانتهاء")),
                (
                    "trainer",
                    models.CharField(blank=True, max_length=100, verbose_name="المدرب"),
                ),
                (
                    "location",
                    models.CharField(blank=True, max_length=100, verbose_name="المكان"),
                ),
                (
                    "capacity",
                    models.PositiveSmallIntegerField(default=20, verbose_name="السعة"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "مجدولة"),
                            ("running", "قيد التنفيذ"),
                            ("completed", "مكتملة"),
                            ("cancelled", "ملغاة"),
                        ],
                        default="planned",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="training.trainingcourse",
                        verbose_name="الدورة",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشأه",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="حدّثه",
                    ),
                ),
            ],
            options={
                "verbose_name": "جلسة تدريبية",
                "verbose_name_plural": "الجلسات التدريبية",
                "ordering": ("-start_date",),
            },
        ),
        migrations.AddField(
            model_name="trainingenrollment",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="training.trainingsession",
                verbose_name="الجلسة",
            ),
        ),
        migrations.AddConstraint(
            model_name="trainingenrollment",
            constraint=models.UniqueConstraint(
                fields=("session", "employee"),
                name="uniq_training_enrollment_session_employee",
            ),
        ),
    ]
