# Generated by Django 5.1.15 on 2026-08-09 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("org", "0002_alter_branch_timezone"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QrDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="حُدّث في"),
                ),
                (
                    "device_code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="رمز الجهاز"
                    ),
                ),
                (
                    "api_key_hash",
                    models.CharField(max_length=128, verbose_name="هاش مفتاح API"),
                ),
                (
                    "location",
                    models.CharField(blank=True, max_length=100, verbose_name="الموقع"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "نشط"),
                            ("inactive", "معطّل"),
                            ("maintenance", "صيانة"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "last_seen",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخر اتصال"
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="qr_devices",
                        to="org.branch",
                        verbose_name="الفرع",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشأه",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="حدّثه",
                    ),
                ),
            ],
            options={
                "verbose_name": "قارئ QR",
                "verbose_name_plural": "قارئات QR",
            },
        ),
        migrations.CreateModel(
            name="QrDeviceAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="حُدّث في"),
                ),
                ("action", models.CharField(max_length=30, verbose_name="الإجراء")),
                ("detail", models.TextField(blank=True, verbose_name="التفاصيل")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشأه",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="devices.qrdevice",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="حدّثه",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل جهاز",
                "verbose_name_plural": "سجلات الأجهزة",
            },
        ),
    ]
