# Generated by Django 5.2.17 on 2026-08-13 11:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BackupJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("manual", "يدوي"),
                            ("daily", "يومي"),
                            ("weekly", "أسبوعي"),
                        ],
                        default="manual",
                        max_length=10,
                        verbose_name="النوع",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "قيد التشغيل"),
                            ("success", "نجحت"),
                            ("failed", "فشلت"),
                        ],
                        default="running",
                        max_length=10,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="ملف النسخة"
                    ),
                ),
                (
                    "file_size",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="الحجم (بايت)"
                    ),
                ),
                (
                    "checksum",
                    models.CharField(blank=True, max_length=64, verbose_name="SHA-256"),
                ),
                ("encrypted", models.BooleanField(default=False, verbose_name="مشفرة")),
                ("error", models.TextField(blank=True, verbose_name="الخطأ")),
                (
                    "started_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="بداية"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="النهاية"),
                ),
                (
                    "duration_seconds",
                    models.FloatField(default=0, verbose_name="المدة (ثواني)"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="backup_jobs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="من قِبَل",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل نسخة",
                "verbose_name_plural": "سجل النسخ",
                "ordering": ("-started_at",),
            },
        ),
        migrations.CreateModel(
            name="BackupSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True, verbose_name="تفعيل النسخ التلقائي"
                    ),
                ),
                (
                    "backup_dir",
                    models.CharField(
                        default="backups", max_length=400, verbose_name="مجلد الوجهة"
                    ),
                ),
                (
                    "retention_count",
                    models.PositiveIntegerField(
                        default=14, verbose_name="عدد النسخ المحتفَظ بها"
                    ),
                ),
                (
                    "encrypt",
                    models.BooleanField(
                        default=True, verbose_name="تشفير النسخ (AES-256-GCM)"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تحديث"),
                ),
                (
                    "notify_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="يُرسل إليه إشعار نجاح/فشل النسخ",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="backup_notify",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="مستخدم الإشعارات (IT)",
                    ),
                ),
            ],
            options={
                "verbose_name": "إعداد النسخ الاحتياطي",
                "verbose_name_plural": "إعدادات النسخ الاحتياطي",
            },
        ),
        migrations.CreateModel(
            name="RestoreJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_file",
                    models.CharField(max_length=500, verbose_name="ملف المصدر"),
                ),
                (
                    "checksum_verified",
                    models.BooleanField(
                        default=False, verbose_name="تم التحقق من checksum"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "نجحت"), ("failed", "فشلت")],
                        default="failed",
                        max_length=10,
                        verbose_name="الحالة",
                    ),
                ),
                ("error", models.TextField(blank=True, verbose_name="الخطأ")),
                (
                    "restored_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="وقت الاستعادة"
                    ),
                ),
                (
                    "restored_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="restore_jobs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="من قِبَل",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل استعادة",
                "verbose_name_plural": "سجل الاستعادة",
                "ordering": ("-restored_at",),
            },
        ),
    ]
