# Generated by Django 5.2.17 on 2026-08-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompanySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name_ar",
                    models.CharField(
                        default="HRMS", max_length=200, verbose_name="اسم الشركة (عربي)"
                    ),
                ),
                (
                    "company_name_fr",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="اسم الشركة (فرنسي)"
                    ),
                ),
                (
                    "company_name_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="اسم الشركة (إنجليزي)"
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True,
                        default="نظام إدارة الموارد البشرية",
                        max_length=300,
                        verbose_name="الشعار النصي",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="branding/",
                        verbose_name="شعار الشركة",
                    ),
                ),
                (
                    "show_logo_watermark",
                    models.BooleanField(
                        default=True,
                        verbose_name="إظهار الشعار في خلفية ورقة طباعة البطاقات",
                    ),
                ),
                (
                    "watermark_opacity",
                    models.PositiveSmallIntegerField(
                        default=8,
                        help_text="قيمة من 0 (شفاف تمامًا) إلى 100 (واضح)",
                        verbose_name="شفافية الشعار في الخلفية (٪)",
                    ),
                ),
            ],
            options={
                "verbose_name": "هوية الشركة",
                "verbose_name_plural": "هوية الشركة",
            },
        ),
    ]
