# Generated by Django 5.2.17 on 2026-08-10 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "إضافة"),
                            ("update", "تعديل"),
                            ("delete", "حذف"),
                            ("login", "دخول"),
                            ("logout", "خروج"),
                            ("export", "تصدير"),
                            ("import", "استيراد"),
                        ],
                        max_length=20,
                        verbose_name="الإجراء",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="النموذج"
                    ),
                ),
                (
                    "object_id",
                    models.CharField(blank=True, max_length=50, verbose_name="المعرّف"),
                ),
                (
                    "object_repr",
                    models.CharField(blank=True, max_length=255, verbose_name="الوصف"),
                ),
                ("detail", models.TextField(blank=True, verbose_name="التفاصيل")),
                (
                    "ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="العنوان IP"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="في"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_entries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل تدقيق",
                "verbose_name_plural": "سجل التدقيق",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["model_name", "-created_at"],
                        name="core_auditl_model_n_a83f3d_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="core_auditl_user_id_969660_idx",
                    ),
                ],
            },
        ),
    ]
