# Generated by Django 5.2.17 on 2026-09-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_audit_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="companysettings",
            name="css_overrides",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='تجاوزات متغيرات CSS للهوية مثل {"--brand": "#2E96C8"} — تُحقن أعلى كل صفحة.',
                verbose_name="تخصيص الألوان",
            ),
        ),
    ]
