# Generated by Django 5.1.15 on 2026-08-09 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("employees", "0004_employeeqr"),
        ("org", "0002_alter_branch_timezone"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="حُدّث في"),
                ),
                (
                    "code",
                    models.CharField(max_length=30, unique=True, verbose_name="الرمز"),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=150, verbose_name="الاسم (عربي)"),
                ),
                (
                    "name_fr",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="الاسم (فرنسي)"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="الاسم (إنجليزي)"
                    ),
                ),
                (
                    "days_per_year",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="أيام السنة"
                    ),
                ),
                (
                    "carryover_allowed",
                    models.BooleanField(default=False, verbose_name="الترحيل مسموح"),
                ),
                (
                    "max_carryover_days",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="أقصى ترحيل"
                    ),
                ),
                (
                    "is_unpaid",
                    models.BooleanField(default=False, verbose_name="غير مدفوعة"),
                ),
                (
                    "requires_approval_levels",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="مستويات الموافقة"
                    ),
                ),
                (
                    "applicable_to",
                    models.CharField(
                        choices=[
                            ("all", "الجميع"),
                            ("gender_male", "ذكور"),
                            ("gender_female", "إناث"),
                        ],
                        default="all",
                        max_length=30,
                        verbose_name="تطبق على",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشأه",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="حدّثه",
                    ),
                ),
            ],
            options={
                "verbose_name": "نوع إجازة",
                "verbose_name_plural": "أنواع الإجازات",
            },
        ),
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="حُدّث في"),
                ),
                ("from_date", models.DateField(verbose_name="من")),
                ("to_date", models.DateField(verbose_name="إلى")),
                (
                    "days",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        max_digits=5,
                        verbose_name="عدد الأيام",
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="السبب")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("pending", "قيد الانتظار"),
                            ("approved", "معتمدة"),
                            ("rejected", "مرفوضة"),
                            ("cancelled", "ملغاة"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "current_level",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="المستوى الحالي"
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="أُرسل في"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشأه",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leave_requests",
                        to="employees.employee",
                        verbose_name="الموظف",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="الطالب",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="حدّثه",
                    ),
                ),
                (
                    "leave_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requests",
                        to="leave.leavetype",
                        verbose_name="نوع الإجازة",
                    ),
                ),
            ],
            options={
                "verbose_name": "طلب إجازة",
                "verbose_name_plural": "طلبات الإجازات",
            },
        ),
        migrations.CreateModel(
            name="LeaveBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="حُدّث في"),
                ),
                ("year", models.PositiveSmallIntegerField(verbose_name="السنة")),
                (
                    "granted",
                    models.DecimalField(
                        decimal_places=1, default=0, max_digits=5, verbose_name="ممنوح"
                    ),
                ),
                (
                    "used",
                    models.DecimalField(
                        decimal_places=1, default=0, max_digits=5, verbose_name="مستعمل"
                    ),
                ),
                (
                    "carried_from",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        max_digits=5,
                        verbose_name="مُرحّل من السابق",
                    ),
                ),
                (
                    "adjusted",
                    models.DecimalField(
                        decimal_places=1, default=0, max_digits=5, verbose_name="تسوية"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشأه",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_balances",
                        to="employees.employee",
                        verbose_name="الموظف",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="حدّثه",
                    ),
                ),
                (
                    "leave_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="balances",
                        to="leave.leavetype",
                        verbose_name="نوع الإجازة",
                    ),
                ),
            ],
            options={
                "verbose_name": "رصيد إجازة",
                "verbose_name_plural": "أرصدة الإجازات",
            },
        ),
        migrations.CreateModel(
            name="PublicHoliday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="حُدّث في"),
                ),
                ("date", models.DateField(verbose_name="التاريخ")),
                (
                    "name_ar",
                    models.CharField(max_length=150, verbose_name="الاسم (عربي)"),
                ),
                (
                    "name_fr",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="الاسم (فرنسي)"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="الاسم (إنجليزي)"
                    ),
                ),
                (
                    "is_recurring",
                    models.BooleanField(default=False, verbose_name="تتكرر سنويًا"),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_holidays",
                        to="org.branch",
                        verbose_name="الفرع",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشأه",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="حدّثه",
                    ),
                ),
            ],
            options={
                "verbose_name": "عطلة رسمية",
                "verbose_name_plural": "العطل الرسمية",
            },
        ),
        migrations.CreateModel(
            name="LeaveApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="حُدّث في"),
                ),
                ("level", models.PositiveSmallIntegerField(verbose_name="المستوى")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("approved", "اعتماد"),
                            ("rejected", "رفض"),
                            ("escalated", "تصعيد"),
                        ],
                        max_length=20,
                        verbose_name="الإجراء",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="ملاحظة")),
                ("at", models.DateTimeField(auto_now_add=True, verbose_name="في")),
                (
                    "approver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المعتمد",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشأه",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="حدّثه",
                    ),
                ),
                (
                    "leave_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="leave.leaverequest",
                        verbose_name="الطلب",
                    ),
                ),
            ],
            options={
                "verbose_name": "موافقة إجازة",
                "verbose_name_plural": "موافقات الإجازات",
                "unique_together": {("leave_request", "level")},
            },
        ),
        migrations.AddIndex(
            model_name="leaverequest",
            index=models.Index(
                fields=["-submitted_at"], name="leave_leave_submitt_572afd_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="leavebalance",
            unique_together={("employee", "leave_type", "year")},
        ),
        migrations.AlterUniqueTogether(
            name="publicholiday",
            unique_together={("branch", "date")},
        ),
    ]
