# Generated by Django 5.2.17 on 2026-09-19 11:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0008_employee_employees_e_employe_8449d4_idx"),
        ("leave", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="leaverequest",
            index=models.Index(fields=["status"], name="leave_leave_status_74e6de_idx"),
        ),
        migrations.AddIndex(
            model_name="leaverequest",
            index=models.Index(
                fields=["employee", "status"], name="leave_leave_employe_521ced_idx"
            ),
        ),
    ]
