# Generated by Django 5.1.15 on 2026-08-08 21:33

import apps.auth_app.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="حُدّث في"),
                ),
                (
                    "code",
                    models.CharField(max_length=100, unique=True, verbose_name="الكود"),
                ),
                ("module", models.CharField(max_length=50, verbose_name="الوحدة")),
                (
                    "name_ar",
                    models.CharField(max_length=150, verbose_name="الاسم (عربي)"),
                ),
                (
                    "name_fr",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="الاسم (فرنسي)"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="الاسم (إنجليزي)"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
            ],
            options={
                "verbose_name": "صلاحية",
                "verbose_name_plural": "الصلاحيات",
            },
        ),
        migrations.CreateModel(
            name="RoleMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="حُدّث في"),
                ),
                (
                    "effective_from",
                    models.DateField(blank=True, null=True, verbose_name="ساري من"),
                ),
                (
                    "effective_to",
                    models.DateField(blank=True, null=True, verbose_name="ساري حتى"),
                ),
            ],
            options={
                "verbose_name": "تعيين دور",
                "verbose_name_plural": "تعيينات الأدوار",
            },
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "صلاحية دور",
                "verbose_name_plural": "صلاحيات الأدوار",
            },
        ),
        migrations.CreateModel(
            name="UserPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("grant", "منح"), ("deny", "منع")],
                        default="grant",
                        max_length=5,
                        verbose_name="الإجراء",
                    ),
                ),
            ],
            options={
                "verbose_name": "استثناء صلاحية",
                "verbose_name_plural": "استثناءات الصلاحيات",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="حُدّث في"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        unique=True,
                        verbose_name="البريد الإلكتروني",
                    ),
                ),
                (
                    "mfa_enabled",
                    models.BooleanField(default=False, verbose_name="MFA مفعّل"),
                ),
                (
                    "mfa_secret",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=64,
                        null=True,
                        verbose_name="سر MFA",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("ar", "العربية"),
                            ("fr", "Français"),
                            ("en", "English"),
                        ],
                        default="ar",
                        max_length=5,
                        verbose_name="اللغة",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="Africa/Algiers",
                        max_length=64,
                        verbose_name="المنطقة الزمنية",
                    ),
                ),
                (
                    "failed_attempts",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="محاولات فاشلة"
                    ),
                ),
                (
                    "locked_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="مقفل حتى"
                    ),
                ),
                (
                    "password_changed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخر تغيير لكلمة المرور"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "مستخدم",
                "verbose_name_plural": "المستخدمون",
            },
            managers=[
                ("objects", apps.auth_app.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="حُدّث في"),
                ),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="الرمز"),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=150, verbose_name="الاسم (عربي)"),
                ),
                (
                    "name_fr",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="الاسم (فرنسي)"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="الاسم (إنجليزي)"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "is_system",
                    models.BooleanField(default=False, verbose_name="دور مدمج"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="auth_app.role",
                        verbose_name="دور أب (ميراث)",
                    ),
                ),
            ],
            options={
                "verbose_name": "دور",
                "verbose_name_plural": "الأدوار",
            },
        ),
    ]
