# Generated by Django 5.1.15 on 2026-08-08 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("employees", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="حُدّث في"),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="رمز الفرع"
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=150, verbose_name="الاسم (عربي)"),
                ),
                (
                    "name_fr",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="الاسم (فرنسي)"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="الاسم (إنجليزي)"
                    ),
                ),
                (
                    "country",
                    models.CharField(blank=True, max_length=100, verbose_name="الدولة"),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="المدينة"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="العنوان")),
                (
                    "timezone",
                    models.CharField(
                        default="Africa/Algiers",
                        max_length=64,
                        verbose_name="المنطقة الزمنية",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشأه",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="حدّثه",
                    ),
                ),
            ],
            options={
                "verbose_name": "فرع",
                "verbose_name_plural": "الفروع",
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="حُدّث في"),
                ),
                ("code", models.CharField(max_length=30, verbose_name="رمز القسم")),
                (
                    "name_ar",
                    models.CharField(max_length=150, verbose_name="الاسم (عربي)"),
                ),
                (
                    "name_fr",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="الاسم (فرنسي)"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="الاسم (إنجليزي)"
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="departments",
                        to="org.branch",
                        verbose_name="الفرع",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشأه",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_departments",
                        to="employees.employee",
                        verbose_name="مدير القسم",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="org.department",
                        verbose_name="القسم الأب",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="حدّثه",
                    ),
                ),
            ],
            options={
                "verbose_name": "قسم",
                "verbose_name_plural": "الأقسام",
                "unique_together": {("branch", "code")},
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="حُدّث في"),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="رمز المنصب"
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=150, verbose_name="الاسم (عربي)"),
                ),
                (
                    "name_fr",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="الاسم (فرنسي)"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="الاسم (إنجليزي)"
                    ),
                ),
                (
                    "grade",
                    models.CharField(blank=True, max_length=20, verbose_name="الدرجة"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشأه",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="positions",
                        to="org.department",
                        verbose_name="القسم",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="حدّثه",
                    ),
                ),
            ],
            options={
                "verbose_name": "منصب",
                "verbose_name_plural": "المناصب",
            },
        ),
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="حُدّث في"),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="رمز الدوام"
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=150, verbose_name="الاسم (عربي)"),
                ),
                (
                    "name_fr",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="الاسم (فرنسي)"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="الاسم (إنجليزي)"
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="بداية الدوام")),
                ("end_time", models.TimeField(verbose_name="نهاية الدوام")),
                (
                    "is_flexible",
                    models.BooleanField(default=False, verbose_name="دوام مرن"),
                ),
                (
                    "grace_minutes",
                    models.PositiveSmallIntegerField(
                        default=10, verbose_name="سماحية التأخير (دقيقة)"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشأه",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="حدّثه",
                    ),
                ),
            ],
            options={
                "verbose_name": "جدول دوام",
                "verbose_name_plural": "جداول الدوام",
            },
        ),
    ]
