# Generated by Django 5.1.15 on 2026-08-08 21:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("org", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branch",
            name="timezone",
            field=models.CharField(
                blank=True,
                default="Africa/Algiers",
                max_length=64,
                verbose_name="المنطقة الزمنية",
            ),
        ),
    ]
