# Generated by Django 5.1.15 on 2026-08-09 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduledAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(max_length=30, verbose_name="نوع التنبيه"),
                ),
                ("target_date", models.DateField(verbose_name="تاريخ الاستهداف")),
                (
                    "payload_json",
                    models.JSONField(blank=True, default=dict, verbose_name="الحمولة"),
                ),
                (
                    "fired_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="أُطلق في"
                    ),
                ),
            ],
            options={
                "verbose_name": "تنبيه مؤجل",
                "verbose_name_plural": "التنبيهات المؤجلة",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("leave_submitted", "طلب إجازة جديد"),
                            ("leave_approved", "اعتماد إجازة"),
                            ("leave_rejected", "رفض إجازة"),
                            ("leave_cancelled", "إلغاء إجازة"),
                            ("attendance_warning", "تنبيه حضور"),
                            ("system", "نظام"),
                        ],
                        default="system",
                        max_length=30,
                        verbose_name="النوع",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="العنوان")),
                ("body", models.TextField(blank=True, verbose_name="النص")),
                (
                    "related_model",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="النموذج المرتبط"
                    ),
                ),
                (
                    "related_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="المعرّف المرتبط"
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="مقروء")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "إشعار",
                "verbose_name_plural": "الإشعارات",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="notif_notif_user_id_c443ee_idx",
                    ),
                    models.Index(
                        fields=["user", "is_read"],
                        name="notif_notif_user_id_29a334_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificationPref",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("leave_submitted", "طلب إجازة جديد"),
                            ("leave_approved", "اعتماد إجازة"),
                            ("leave_rejected", "رفض إجازة"),
                            ("leave_cancelled", "إلغاء إجازة"),
                            ("attendance_warning", "تنبيه حضور"),
                            ("system", "نظام"),
                        ],
                        max_length=30,
                        verbose_name="النوع",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("in_app", "داخل التطبيق"), ("email", "بريد")],
                        default="in_app",
                        max_length=20,
                        verbose_name="القناة",
                    ),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="مفعّل")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_prefs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "تفضيل إشعار",
                "verbose_name_plural": "تفضيلات الإشعارات",
                "unique_together": {("user", "type", "channel")},
            },
        ),
    ]
