# Generated by Django 5.2.17 on 2026-08-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notif", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledalert",
            name="reference",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="المرجع"
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("leave_submitted", "طلب إجازة جديد"),
                    ("leave_approved", "اعتماد إجازة"),
                    ("leave_rejected", "رفض إجازة"),
                    ("leave_cancelled", "إلغاء إجازة"),
                    ("attendance_warning", "تنبيه حضور"),
                    ("contract_expiring", "انتهاء عقد"),
                    ("document_expiring", "انتهاء صلاحية وثيقة"),
                    ("probation_end", "نهاية فترة التجربة"),
                    ("system", "نظام"),
                ],
                default="system",
                max_length=30,
                verbose_name="النوع",
            ),
        ),
        migrations.AlterField(
            model_name="notificationpref",
            name="type",
            field=models.CharField(
                choices=[
                    ("leave_submitted", "طلب إجازة جديد"),
                    ("leave_approved", "اعتماد إجازة"),
                    ("leave_rejected", "رفض إجازة"),
                    ("leave_cancelled", "إلغاء إجازة"),
                    ("attendance_warning", "تنبيه حضور"),
                    ("contract_expiring", "انتهاء عقد"),
                    ("document_expiring", "انتهاء صلاحية وثيقة"),
                    ("probation_end", "نهاية فترة التجربة"),
                    ("system", "نظام"),
                ],
                max_length=30,
                verbose_name="النوع",
            ),
        ),
        migrations.AddConstraint(
            model_name="scheduledalert",
            constraint=models.UniqueConstraint(
                fields=("alert_type", "target_date", "reference"),
                name="uniq_scheduled_alert",
            ),
        ),
    ]
