# Generated by Django 5.2.17 on 2026-08-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notif", "0002_scheduledalert_reference_alter_notification_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("leave_submitted", "طلب إجازة جديد"),
                    ("leave_approved", "اعتماد إجازة"),
                    ("leave_rejected", "رفض إجازة"),
                    ("leave_cancelled", "إلغاء إجازة"),
                    ("attendance_warning", "تنبيه حضور"),
                    ("contract_expiring", "انتهاء عقد"),
                    ("document_expiring", "انتهاء صلاحية وثيقة"),
                    ("probation_end", "نهاية فترة التجربة"),
                    ("training_enrollment", "تسجيل تدريبي"),
                    ("training_certificate", "شهادة تدريب"),
                    ("system", "نظام"),
                ],
                default="system",
                max_length=30,
                verbose_name="النوع",
            ),
        ),
        migrations.AlterField(
            model_name="notificationpref",
            name="type",
            field=models.CharField(
                choices=[
                    ("leave_submitted", "طلب إجازة جديد"),
                    ("leave_approved", "اعتماد إجازة"),
                    ("leave_rejected", "رفض إجازة"),
                    ("leave_cancelled", "إلغاء إجازة"),
                    ("attendance_warning", "تنبيه حضور"),
                    ("contract_expiring", "انتهاء عقد"),
                    ("document_expiring", "انتهاء صلاحية وثيقة"),
                    ("probation_end", "نهاية فترة التجربة"),
                    ("training_enrollment", "تسجيل تدريبي"),
                    ("training_certificate", "شهادة تدريب"),
                    ("system", "نظام"),
                ],
                max_length=30,
                verbose_name="النوع",
            ),
        ),
    ]
