# Generated by Django 5.1.15 on 2026-08-09 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("employees", "0004_employeeqr"),
        ("org", "0002_alter_branch_timezone"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="حُدّث في"),
                ),
                ("work_date", models.DateField(verbose_name="تاريخ العمل")),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("present", "حاضر"),
                            ("absent", "غائب"),
                            ("leave", "إجازة"),
                            ("mission", "مأمورية"),
                            ("exception", "استثناء"),
                            ("weekend", "عطلة"),
                        ],
                        default="present",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "check_in",
                    models.DateTimeField(blank=True, null=True, verbose_name="دخول"),
                ),
                (
                    "check_out",
                    models.DateTimeField(blank=True, null=True, verbose_name="خروج"),
                ),
                (
                    "worked_minutes",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="دقائق العمل"
                    ),
                ),
                (
                    "late_minutes",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="دقائق التأخير"
                    ),
                ),
                (
                    "early_minutes",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="دقائق الخروج المبكر"
                    ),
                ),
                (
                    "overtime_minutes",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="دقائق إضافية"
                    ),
                ),
                (
                    "is_corrected",
                    models.BooleanField(default=False, verbose_name="مُصحّح"),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="org.branch",
                        verbose_name="الفرع",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشأه",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_days",
                        to="employees.employee",
                        verbose_name="الموظف",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="org.shift",
                        verbose_name="جدول الدوام",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="حدّثه",
                    ),
                ),
            ],
            options={
                "verbose_name": "يوم حضور",
                "verbose_name_plural": "أيام الحضور",
            },
        ),
        migrations.CreateModel(
            name="AttendanceException",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="حُدّث في"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("permission", "إذن"),
                            ("mission", "مأمورية"),
                            ("compensatory", "تعويض"),
                            ("correction", "تصحيح"),
                        ],
                        default="permission",
                        max_length=20,
                        verbose_name="النوع",
                    ),
                ),
                ("from_time", models.DateTimeField(verbose_name="من")),
                ("to_time", models.DateTimeField(verbose_name="إلى")),
                (
                    "hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="الساعات",
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="السبب")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد الانتظار"),
                            ("approved", "معتمد"),
                            ("rejected", "مرفوض"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المعتمد",
                    ),
                ),
                (
                    "attendanceday",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exceptions",
                        to="attendance.attendanceday",
                        verbose_name="يوم الحضور",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشأه",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_exceptions",
                        to="employees.employee",
                        verbose_name="الموظف",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="الطالب",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="حدّثه",
                    ),
                ),
            ],
            options={
                "verbose_name": "استثناء حضور",
                "verbose_name_plural": "استثناءات الحضور",
            },
        ),
        migrations.CreateModel(
            name="AttendanceScan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="حُدّث في"),
                ),
                (
                    "scanned_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمن المسح"),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("phone", "هاتف"),
                            ("fixed_reader", "قارئ ثابت"),
                            ("manual", "يدوي"),
                        ],
                        default="phone",
                        max_length=20,
                        verbose_name="المصدر",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="عنوان IP"
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("check_in", "دخول"),
                            ("check_out", "خروج"),
                            ("rejected", "مرفوض"),
                            ("warning", "تحذير"),
                        ],
                        max_length=20,
                        verbose_name="القرار",
                    ),
                ),
                (
                    "qr_version",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="إصدار QR"
                    ),
                ),
                (
                    "result_detail",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="السبب/النتيجة"
                    ),
                ),
                (
                    "attendanceday",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scans",
                        to="attendance.attendanceday",
                        verbose_name="يوم الحضور",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشأه",
                    ),
                ),
            ],
            options={
                "verbose_name": "عملية مسح",
                "verbose_name_plural": "عمليات المسح",
            },
        ),
    ]
