# Generated by Django 5.2.17 on 2026-08-13 15:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendancescan",
            name="scanned_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="زمن المسح"
            ),
        ),
    ]
