# Generated by Django 5.2.17 on 2026-09-19 11:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0003_alter_attendancescan_scanned_at"),
        ("employees", "0007_contract_document_helpers"),
        ("org", "0002_alter_branch_timezone"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="attendanceday",
            index=models.Index(
                fields=["work_date"], name="attendance__work_da_899fc6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendanceday",
            index=models.Index(
                fields=["branch", "work_date"], name="attendance__branch__2f8721_idx"
            ),
        ),
    ]
