# Generated by Django 5.2.17 on 2026-08-13 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("employees", "0007_contract_document_helpers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt", models.TextField(verbose_name="السؤال")),
                (
                    "answer_json",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="الإجابة (JSON)"
                    ),
                ),
                (
                    "language",
                    models.CharField(default="ar", max_length=5, verbose_name="اللغة"),
                ),
                (
                    "analytics_ref",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="مرجع تحليلي"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="في"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_queries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "سؤال ذكي",
                "verbose_name_plural": "الأسئلة الذكية",
            },
        ),
        migrations.CreateModel(
            name="AnalyticsJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "analysis_type",
                    models.CharField(
                        choices=[
                            ("absence", "الغياب"),
                            ("attendance", "الحضور"),
                            ("performance", "الأداء"),
                            ("payroll", "الرواتب"),
                            ("turnover", "التنقل الوظيفي"),
                            ("productivity", "الإنتاجية"),
                        ],
                        max_length=50,
                        verbose_name="نوع التحليل",
                    ),
                ),
                (
                    "period_start",
                    models.DateField(
                        blank=True, null=True, verbose_name="بداية الفترة"
                    ),
                ),
                (
                    "period_end",
                    models.DateField(
                        blank=True, null=True, verbose_name="نهاية الفترة"
                    ),
                ),
                (
                    "scope_json",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="النطاق (JSON)"
                    ),
                ),
                (
                    "result_json",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="النتيجة (JSON)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "بانتظار التنفيذ"),
                            ("running", "قيد التنفيذ"),
                            ("done", "مكتمل"),
                            ("failed", "فشل"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                ("error", models.TextField(blank=True, verbose_name="الخطأ")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئت في"),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="طلبها",
                    ),
                ),
            ],
            options={
                "verbose_name": "مهمة تحليل",
                "verbose_name_plural": "مهام التحليل",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="AIPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prediction_type",
                    models.CharField(
                        choices=[
                            ("resignation", "مخاطر الاستقالة"),
                            ("absence_risk", "مخاطر الغياب"),
                        ],
                        default="resignation",
                        max_length=20,
                        verbose_name="نوع التنبؤ",
                    ),
                ),
                (
                    "probability",
                    models.DecimalField(
                        decimal_places=3, max_digits=4, verbose_name="الاحتمال"
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("low", "منخفض"),
                            ("medium", "متوسط"),
                            ("high", "مرتفع"),
                        ],
                        default="low",
                        max_length=20,
                        verbose_name="المستوى",
                    ),
                ),
                (
                    "features_json",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="الخصائص (JSON)"
                    ),
                ),
                (
                    "model_version",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="إصدار النموذج"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_predictions",
                        to="employees.employee",
                        verbose_name="الموظف",
                    ),
                ),
            ],
            options={
                "verbose_name": "تنبؤ ذكي",
                "verbose_name_plural": "التنبؤات الذكية",
                "ordering": ("-created_at",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("employee", "prediction_type"),
                        name="uniq_ai_prediction_employee_type",
                    )
                ],
            },
        ),
    ]
