# Generated by Django 5.2.17 on 2026-08-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiquery",
            name="was_helpful",
            field=models.BooleanField(
                blank=True,
                help_text="تقييم المستخدم (نعم/لا) — يدخل في حلقة تحسين المساعد",
                null=True,
                verbose_name="مفيدة؟",
            ),
        ),
        migrations.AlterField(
            model_name="analyticsjob",
            name="analysis_type",
            field=models.CharField(
                choices=[
                    ("kpi_dashboard", "لوحة المؤشرات"),
                    ("absence", "الغياب"),
                    ("attendance", "الحضور"),
                    ("performance", "الأداء"),
                    ("payroll", "الرواتب"),
                    ("turnover", "التنقل الوظيفي"),
                    ("productivity", "الإنتاجية"),
                ],
                max_length=50,
                verbose_name="نوع التحليل",
            ),
        ),
    ]
