# Generated by Django 5.2.17 on 2026-08-13 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("employees", "0007_contract_document_helpers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PerfCycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="حُدّث في"),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=150, verbose_name="الاسم (عربي)"),
                ),
                (
                    "name_fr",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="الاسم (فرنسي)"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="الاسم (إنجليزي)"
                    ),
                ),
                ("period_start", models.DateField(verbose_name="بداية الفترة")),
                ("period_end", models.DateField(verbose_name="نهاية الفترة")),
                (
                    "self_review_deadline",
                    models.DateField(
                        blank=True, null=True, verbose_name="آخر موعد للتقييم الذاتي"
                    ),
                ),
                (
                    "manager_review_deadline",
                    models.DateField(
                        blank=True, null=True, verbose_name="آخر موعد لتقييم المدير"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("open", "مفتوحة"),
                            ("closed", "مغلقة"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشأه",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="حدّثه",
                    ),
                ),
            ],
            options={
                "verbose_name": "دورة تقييم",
                "verbose_name_plural": "دورات التقييم",
                "ordering": ("-period_start",),
            },
        ),
        migrations.CreateModel(
            name="PerfReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="حُدّث في"),
                ),
                (
                    "self_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="درجة التقييم الذاتي",
                    ),
                ),
                (
                    "manager_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="درجة المدير",
                    ),
                ),
                (
                    "final_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="الدرجة النهائية",
                    ),
                ),
                (
                    "self_comment",
                    models.TextField(blank=True, verbose_name="تعليق الموظف"),
                ),
                (
                    "manager_comment",
                    models.TextField(blank=True, verbose_name="تعليق المدير"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_self", "بانتظار التقييم الذاتي"),
                            ("pending_manager", "بانتظار تقييم المدير"),
                            ("done", "مكتمل"),
                            ("closed", "مغلق"),
                        ],
                        default="pending_self",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشأه",
                    ),
                ),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="perf.perfcycle",
                        verbose_name="الدورة",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perf_reviews",
                        to="employees.employee",
                        verbose_name="الموظف",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="حدّثه",
                    ),
                ),
            ],
            options={
                "verbose_name": "مراجعة تقييم",
                "verbose_name_plural": "مراجعات التقييم",
                "ordering": ("employee__employee_code",),
            },
        ),
        migrations.CreateModel(
            name="PerfObjective",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="حُدّث في"),
                ),
                (
                    "kpi_title",
                    models.CharField(max_length=200, verbose_name="عنوان الهدف/KPI"),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=100,
                        max_digits=5,
                        verbose_name="الوزن (٪)",
                    ),
                ),
                (
                    "target",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="الهدف",
                    ),
                ),
                (
                    "achieved",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="المحقق",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="الدرجة (من 100)",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشأه",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="حدّثه",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="objectives",
                        to="perf.perfreview",
                        verbose_name="المراجعة",
                    ),
                ),
            ],
            options={
                "verbose_name": "هدف أداء",
                "verbose_name_plural": "أهداف الأداء",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="PerfTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="حُدّث في"),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=150, verbose_name="الاسم (عربي)"),
                ),
                (
                    "name_fr",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="الاسم (فرنسي)"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="الاسم (إنجليزي)"
                    ),
                ),
                (
                    "criteria_json",
                    models.JSONField(
                        blank=True, default=list, verbose_name="المعايير (بالأوزان)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشأه",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="حدّثه",
                    ),
                ),
            ],
            options={
                "verbose_name": "قالب تقييم",
                "verbose_name_plural": "قوالب التقييم",
                "ordering": ("name_ar",),
            },
        ),
        migrations.AddField(
            model_name="perfreview",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviews",
                to="perf.perftemplate",
                verbose_name="القالب",
            ),
        ),
        migrations.CreateModel(
            name="PipPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="حُدّث في"),
                ),
                ("start_date", models.DateField(verbose_name="تاريخ البدء")),
                ("end_date", models.DateField(verbose_name="تاريخ الانتهاء")),
                ("action_items", models.TextField(verbose_name="بنود التحسين")),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "مفتوحة"), ("closed", "مغلقة")],
                        default="open",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "supervisor_note",
                    models.TextField(blank=True, verbose_name="ملاحظة المشرف"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشأه",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pip_plans",
                        to="perf.perfreview",
                        verbose_name="المراجعة",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="حدّثه",
                    ),
                ),
            ],
            options={
                "verbose_name": "خطة تحسين أداء",
                "verbose_name_plural": "خطط تحسين الأداء",
                "ordering": ("-start_date",),
            },
        ),
        migrations.AddConstraint(
            model_name="perfreview",
            constraint=models.UniqueConstraint(
                fields=("employee", "cycle"), name="uniq_perf_review_employee_cycle"
            ),
        ),
    ]
