# Generated by Django 5.2.17 on 2026-08-13 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth_app", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="حُدّث في"),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="رمز التقرير"
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=150, verbose_name="الاسم (عربي)"),
                ),
                (
                    "name_fr",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="الاسم (فرنسي)"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="الاسم (إنجليزي)"
                    ),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("xlsx", "Excel"), ("csv", "CSV")],
                        default="pdf",
                        max_length=10,
                        verbose_name="الصيغة",
                    ),
                ),
                (
                    "filters_json",
                    models.JSONField(blank=True, default=dict, verbose_name="الفلاتر"),
                ),
                ("is_shared", models.BooleanField(default=False, verbose_name="مشترك")),
                (
                    "schedule",
                    models.CharField(
                        choices=[
                            ("manual", "يدوي"),
                            ("daily", "يومي"),
                            ("weekly", "أسبوعي"),
                            ("monthly", "شهري"),
                        ],
                        default="manual",
                        max_length=10,
                        verbose_name="الجدولة",
                    ),
                ),
                (
                    "run_at",
                    models.TimeField(blank=True, null=True, verbose_name="وقت التنفيذ"),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="يوم الأسبوع (0=الأحد)"
                    ),
                ),
                (
                    "day_of_month",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="يوم الشهر (1-31)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "last_run_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخر تنفيذ"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشأه",
                    ),
                ),
                (
                    "notify_roles",
                    models.ManyToManyField(
                        blank=True,
                        related_name="scheduled_reports",
                        to="auth_app.role",
                        verbose_name="أدوار المستلمين",
                    ),
                ),
                (
                    "notify_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="scheduled_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="مستلمو الإشعار",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="report_definitions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المالك",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="حدّثه",
                    ),
                ),
            ],
            options={
                "verbose_name": "تقرير مجدول",
                "verbose_name_plural": "التقارير المجدولة",
            },
        ),
        migrations.CreateModel(
            name="ReportJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="حُدّث في"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "في الانتظار"),
                            ("running", "قيد التنفيذ"),
                            ("done", "مكتمل"),
                            ("failed", "فشل"),
                        ],
                        default="queued",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="البداية"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="النهاية"),
                ),
                ("error", models.TextField(blank=True, verbose_name="الخطأ")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشأه",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="reports.reportdefinition",
                        verbose_name="التقرير",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="report_jobs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="طلب التنفيذ",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="حدّثه",
                    ),
                ),
            ],
            options={
                "verbose_name": "تنفيذ تقرير",
                "verbose_name_plural": "تنفيذات التقارير",
                "ordering": ("-started_at",),
            },
        ),
        migrations.CreateModel(
            name="ReportGeneratedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_path", models.CharField(max_length=500, verbose_name="المسار")),
                ("format", models.CharField(max_length=10, verbose_name="الصيغة")),
                (
                    "size_bytes",
                    models.BigIntegerField(default=0, verbose_name="الحجم (بايت)"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="انتهاء الصلاحية"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="reports.reportjob",
                        verbose_name="التنفيذ",
                    ),
                ),
            ],
            options={
                "verbose_name": "ملف تقرير",
                "verbose_name_plural": "ملفات التقارير",
            },
        ),
    ]
