# Generated by Django 5.1.15 on 2026-08-09 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("employees", "0005_employee_bank_account"),
        ("org", "0002_alter_branch_timezone"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EndOfService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="حُدّث في"),
                ),
                ("termination_date", models.DateField(verbose_name="تاريخ النهاية")),
                (
                    "total_years",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="إجمالي السنوات",
                    ),
                ),
                (
                    "service_reward",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="مكافأة الخدمة",
                    ),
                ),
                (
                    "unused_leave_comp",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="تعويض الإجازات المتبقية",
                    ),
                ),
                (
                    "notice_period",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="بدل الإشعار",
                    ),
                ),
                (
                    "deductions",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="الخصومات",
                    ),
                ),
                (
                    "net",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="الصافي",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("approved", "معتمد"),
                            ("paid", "مدفوع"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="eos_approved",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="اعتمدها",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشأه",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="end_of_services",
                        to="employees.employee",
                        verbose_name="الموظف",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="حدّثه",
                    ),
                ),
            ],
            options={
                "verbose_name": "نهاية خدمة",
                "verbose_name_plural": "نهايات الخدمة",
            },
        ),
        migrations.CreateModel(
            name="PayElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="حُدّث في"),
                ),
                (
                    "code",
                    models.CharField(max_length=30, unique=True, verbose_name="الرمز"),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=150, verbose_name="الاسم (عربي)"),
                ),
                (
                    "name_fr",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="الاسم (فرنسي)"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="الاسم (إنجليزي)"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("earning", "إضافة"), ("deduction", "خصم")],
                        max_length=10,
                        verbose_name="النوع",
                    ),
                ),
                (
                    "calculation",
                    models.CharField(
                        choices=[
                            ("fixed", "مبلغ ثابت"),
                            ("percent_of_basic", "نسبة من الأساسي"),
                            ("attendance_based", "حسب الحضور"),
                        ],
                        default="fixed",
                        max_length=20,
                        verbose_name="طريقة الحساب",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="المبلغ",
                    ),
                ),
                (
                    "percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="النسبة %",
                    ),
                ),
                (
                    "applies_to_all",
                    models.BooleanField(default=True, verbose_name="يطبق على الجميع"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشأه",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="حدّثه",
                    ),
                ),
            ],
            options={
                "verbose_name": "عنصر أجر",
                "verbose_name_plural": "عناصر الأجر",
            },
        ),
        migrations.CreateModel(
            name="PayRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="حُدّث في"),
                ),
                (
                    "period_code",
                    models.CharField(
                        help_text="مثال: 2026-08",
                        max_length=10,
                        verbose_name="فترة الرواتب",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("reviewing", "قيد المراجعة"),
                            ("approved", "معتمد"),
                            ("frozen", "مجمّد"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "total_earnings",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="إجمالي الإضافات",
                    ),
                ),
                (
                    "total_deductions",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="إجمالي الخصومات",
                    ),
                ),
                (
                    "total_net",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="صافي الإجمالي",
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="أُنشئت في"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="وقت الاعتماد"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pay_runs_approved",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="اعتمدها",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pay_runs",
                        to="org.branch",
                        verbose_name="الفرع",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشأه",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pay_runs_generated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشأها",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="حدّثه",
                    ),
                ),
            ],
            options={
                "verbose_name": "دورة رواتب",
                "verbose_name_plural": "دورات الرواتب",
            },
        ),
        migrations.CreateModel(
            name="PayrollLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="حُدّث في"),
                ),
                (
                    "hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="الساعات",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="المبلغ"
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=200, verbose_name="ملاحظة"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشأه",
                    ),
                ),
                (
                    "element",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="payroll.payelement",
                        verbose_name="العنصر",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_lines",
                        to="employees.employee",
                        verbose_name="الموظف",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="حدّثه",
                    ),
                ),
                (
                    "pay_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="payroll.payrun",
                        verbose_name="الدورة",
                    ),
                ),
            ],
            options={
                "verbose_name": "سطر راتب",
                "verbose_name_plural": "أسطر الرواتب",
            },
        ),
        migrations.CreateModel(
            name="Payslip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="حُدّث في"),
                ),
                (
                    "basic_salary",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="الأجر الأساسي"
                    ),
                ),
                (
                    "total_earnings",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="إجمالي الإضافات"
                    ),
                ),
                (
                    "total_deductions",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="إجمالي الخصومات"
                    ),
                ),
                (
                    "net",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="الصافي"
                    ),
                ),
                (
                    "attended_days",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="أيام الحضور"
                    ),
                ),
                (
                    "absent_days",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="أيام الغياب"
                    ),
                ),
                (
                    "leave_days",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="أيام الإجازة"
                    ),
                ),
                (
                    "overtime_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="ساعات إضافية",
                    ),
                ),
                (
                    "bank_export_ref",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="مرجع تصدير البنك"
                    ),
                ),
                (
                    "pdf_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="مسار PDF"
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئت في"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشأه",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payslips",
                        to="employees.employee",
                        verbose_name="الموظف",
                    ),
                ),
                (
                    "pay_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payslips",
                        to="payroll.payrun",
                        verbose_name="الدورة",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="حدّثه",
                    ),
                ),
            ],
            options={
                "verbose_name": "قسيمة راتب",
                "verbose_name_plural": "قسائم الرواتب",
            },
        ),
        migrations.AddConstraint(
            model_name="payrun",
            constraint=models.UniqueConstraint(
                fields=("period_code", "branch"), name="uniq_payrun_period_branch"
            ),
        ),
        migrations.AddConstraint(
            model_name="payrollline",
            constraint=models.UniqueConstraint(
                fields=("pay_run", "employee", "element"),
                name="uniq_payrollline_run_emp_elem",
            ),
        ),
        migrations.AddConstraint(
            model_name="payslip",
            constraint=models.UniqueConstraint(
                fields=("pay_run", "employee"), name="uniq_payslip_run_emp"
            ),
        ),
    ]
