# Generated by Django 5.2.17 on 2026-08-10 12:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payroll", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PayrollSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "salary_base_days",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="0 = تُحسب تلقائيًا من تقويم الفترة (الاثنين..الجمعة − العطل الرسمية). عند ضبطها (مثل 26) تُستخدم بدلاً منها في حساب الأجر اليومي (BR-PAY-002).",
                        verbose_name="أيام الأساس للأجر اليومي",
                    ),
                ),
                (
                    "absence_deduction_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="عند إيقافه لا يُسجَّل خصم آلي على أيام الغياب.",
                        verbose_name="تفعيل خصم الغياب",
                    ),
                ),
                (
                    "absence_grace_days",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="عدد أيام الغياب المعفاة من الخصم كل شهر (يُخصم ما بعدها فقط).",
                        verbose_name="أيام سماح للغياب",
                    ),
                ),
                (
                    "auto_mark_absent",
                    models.BooleanField(
                        default=False,
                        help_text="BR-ATT-004: تُعلَّم أيام العمل التي لا يوجد لها مسح كغياب تلقائيًا (مع استثناء الإجازات المعتمدة والمهام والعطل الرسمية).",
                        verbose_name="العلام التلقائي للغياب عند توليد الرواتب",
                    ),
                ),
                (
                    "eos_reward_factor",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.50"),
                        help_text="مكافأة نهاية الخدمة = سنوات الخدمة × الأجر اليومي × هذا العامل.",
                        max_digits=4,
                        verbose_name="عامل مكافأة نهاية الخدمة",
                    ),
                ),
            ],
            options={
                "verbose_name": "إعدادات الرواتب والخصم",
                "verbose_name_plural": "إعدادات الرواتب والخصم",
            },
        ),
    ]
