# Generated by Django 5.1.15 on 2026-08-08 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="حُدّث في"),
                ),
                (
                    "employee_code",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="رقم الموظف"
                    ),
                ),
                (
                    "first_name_ar",
                    models.CharField(max_length=100, verbose_name="الاسم (عربي)"),
                ),
                (
                    "last_name_ar",
                    models.CharField(max_length=100, verbose_name="اللقب (عربي)"),
                ),
                (
                    "first_name_fr",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="الاسم (فرنسي)"
                    ),
                ),
                (
                    "last_name_fr",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="اللقب (فرنسي)"
                    ),
                ),
                (
                    "first_name_en",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="الاسم (إنجليزي)"
                    ),
                ),
                (
                    "last_name_en",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="اللقب (إنجليزي)"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "ذكر"), ("F", "أنثى")],
                        max_length=1,
                        verbose_name="الجنس",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ الميلاد"
                    ),
                ),
                (
                    "hire_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ التوظيف"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=30, verbose_name="الهاتف"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="البريد الإلكتروني"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="العنوان")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="employees/photos/",
                        verbose_name="الصورة",
                    ),
                ),
                (
                    "employment_status",
                    models.CharField(
                        choices=[
                            ("active", "نشط"),
                            ("probation", "تحت التجربة"),
                            ("suspended", "موقوف"),
                            ("terminated", "منتهي"),
                            ("resigned", "مستقيل"),
                            ("retired", "متقاعد"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="الحالة الوظيفية",
                    ),
                ),
            ],
            options={
                "verbose_name": "موظف",
                "verbose_name_plural": "الموظفون",
            },
        ),
        migrations.CreateModel(
            name="EmploymentHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="حُدّث في"),
                ),
                ("effective_from", models.DateField(verbose_name="ساري من")),
                (
                    "effective_to",
                    models.DateField(blank=True, null=True, verbose_name="ساري حتى"),
                ),
                (
                    "is_current",
                    models.BooleanField(default=True, verbose_name="الحالي"),
                ),
            ],
            options={
                "verbose_name": "سجل توظيفي",
                "verbose_name_plural": "السجل الوظيفي",
            },
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="حُدّث في"),
                ),
                (
                    "contract_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="رقم العقد"
                    ),
                ),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("cdi", "عقد دائم"),
                            ("cdd", "عقد محدد المدة"),
                            ("stage", "تدريب"),
                        ],
                        default="cdi",
                        max_length=10,
                        verbose_name="نوع العقد",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="بداية العقد")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="نهاية العقد"),
                ),
                (
                    "gross_salary",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="الأجر الإجمالي"
                    ),
                ),
                (
                    "base_salary",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="الأجر الأساسي"
                    ),
                ),
                (
                    "allowance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="العلاوات",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="DZD", max_length=3, verbose_name="العملة"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشأه",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="حدّثه",
                    ),
                ),
            ],
            options={
                "verbose_name": "عقد",
                "verbose_name_plural": "العقود",
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="حُدّث في"),
                ),
                (
                    "document_type",
                    models.CharField(max_length=50, verbose_name="نوع المستند"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="العنوان")),
                (
                    "file",
                    models.FileField(
                        upload_to="employees/documents/", verbose_name="الملف"
                    ),
                ),
                (
                    "issued_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ الإصدار"
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ الانتهاء"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشأه",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="حدّثه",
                    ),
                ),
            ],
            options={
                "verbose_name": "مستند",
                "verbose_name_plural": "المستندات",
            },
        ),
    ]
