# Generated by Django 5.1.15 on 2026-08-08 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="نشط"),
        ),
    ]
