# Generated by Django 5.1.15 on 2026-08-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0004_employeeqr"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="bank_account",
            field=models.CharField(
                blank=True,
                help_text="لتصدير البنك (FR-PAY-008)",
                max_length=50,
                verbose_name="الحساب البنكي",
            ),
        ),
    ]
