# Generated by Django 5.2.17 on 2026-08-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0005_employee_bank_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="national_id",
            field=models.CharField(
                blank=True,
                help_text="يُعرض على بطاقة الموظف",
                max_length=30,
                verbose_name="رقم الهوية الوطنية",
            ),
        ),
    ]
