# Generated by Django 5.2.17 on 2026-08-10 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0006_employee_national_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="previous_contract",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="renewal",
                to="employees.contract",
                verbose_name="العقد السابق",
            ),
        ),
    ]
