# Generated by Django 5.2.17 on 2026-09-19 11:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0007_contract_document_helpers"),
        ("org", "0002_alter_branch_timezone"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["employee_code", "is_active"],
                name="employees_e_employe_8449d4_idx",
            ),
        ),
    ]
